# Generated by Django 3.2 on 2023-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
