# Generated by Django 3.2 on 2023-04-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
