# Generated by Django 3.2 on 2023-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='emo',
            field=models.TextField(default='未处理'),
        ),
    ]
