# Generated by Django 3.2 on 2023-04-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_news_emo'),
    ]

    operations = [
        migrations.CreateModel(
            name='newss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, unique=True)),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=50)),
                ('emo', models.TextField(max_length=5)),
                ('article', models.TextField()),
            ],
        ),
    ]
