# Generated by Django 3.2 on 2023-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_newss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newss',
        ),
    ]
