# Generated by Django 3.2 on 2023-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0008_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200, unique=True)),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=50)),
                ('emo', models.TextField(max_length=5)),
                ('article', models.TextField()),
            ],
        ),
    ]
